### ISSUE TITLE
Crash on death (1.18.1 forge - 39.0.6)

### ISSUE THREAD

**Issue by Kthan-Graham** [pale-imitations/schools_of_magic#7]
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 12/19/21, 7:14 PM
Description: Ticking player

java.lang.IllegalStateException: null
	at net.minecraftforge.common.util.LazyOptional.orElseThrow(LazyOptional.java:295) ~[forge-1.18.1-39.0.6-universal.jar%2357!:?] {re:classloading}
	at com.paleimitations.schoolsofmagic.common.data.capabilities.magic_data.MagicDataProvider$Events.onUpdate(MagicDataProvider.java:120) ~[SchoolsOfMagic1.18.1-3.0.04.jar%2352!:3.0.04] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_17_Events_onUpdate_LivingUpdateEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!:?] {}
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:283) ~[forge-1.18.1-39.0.6-universal.jar%2357!:?] {re:classloading}
	at net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2204) ~[client-1.18.1-20211210.034407-srg.jar%2353!:?] {re:classloading}
	at net.minecraft.world.entity.player.Player.m_8119_(Player.java:234) ~[client-1.18.1-20211210.034407-srg.jar%2353!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:439) ~[client-1.18.1-20211210.034407-srg.jar%2353!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_9933_(ServerGamePacketListenerImpl.java:206) ~[client-1.18.1-20211210.034407-srg.jar%2353!:?] {re:classloading}
	at net.minecraft.network.Connection.m_129483_(Connection.java:233) ~[client-1.18.1-20211210.034407-srg.jar%2353!:?] {re:classloading}
	at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:142) ~[client-1.18.1-20211210.034407-srg.jar%2353!:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:882) ~[client-1.18.1-20211210.034407-srg.jar%2353!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:808) ~[client-1.18.1-20211210.034407-srg.jar%2353!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:86) ~[client-1.18.1-20211210.034407-srg.jar%2353!:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:668) ~[client-1.18.1-20211210.034407-srg.jar%2353!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[client-1.18.1-20211210.034407-srg.jar%2353!:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraftforge.common.util.LazyOptional.orElseThrow(LazyOptional.java:295) ~[forge-1.18.1-39.0.6-universal.jar%2357!:?] {re:classloading}
	at com.paleimitations.schoolsofmagic.common.data.capabilities.magic_data.MagicDataProvider$Events.onUpdate(MagicDataProvider.java:120) ~[SchoolsOfMagic1.18.1-3.0.04.jar%2352!:3.0.04] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_17_Events_onUpdate_LivingUpdateEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!:?] {}
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:283) ~[forge-1.18.1-39.0.6-universal.jar%2357!:?] {re:classloading}
	at net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2204) ~[client-1.18.1-20211210.034407-srg.jar%2353!:?] {re:classloading}
	at net.minecraft.world.entity.player.Player.m_8119_(Player.java:234) ~[client-1.18.1-20211210.034407-srg.jar%2353!:?] {re:classloading,pl:accesstransformer:B}
-- Player being ticked --
Details:
	Entity Type: minecraft:player (net.minecraft.server.level.ServerPlayer)
	Entity ID: 311
	Entity Name: SirSpongington
	Entity's Exact location: 62.65, 71.00, -37.91
	Entity's Block location: World: (62,71,-38), Section: (at 14,7,10 in 3,4,-3; chunk contains blocks 48,-64,-48 to 63,319,-33), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Entity's Momentum: 0.00, -0.16, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:439) ~[client-1.18.1-20211210.034407-srg.jar%2353!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_9933_(ServerGamePacketListenerImpl.java:206) ~[client-1.18.1-20211210.034407-srg.jar%2353!:?] {re:classloading}
	at net.minecraft.network.Connection.m_129483_(Connection.java:233) ~[client-1.18.1-20211210.034407-srg.jar%2353!:?] {re:classloading}
	at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:142) ~[client-1.18.1-20211210.034407-srg.jar%2353!:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:882) ~[client-1.18.1-20211210.034407-srg.jar%2353!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:808) ~[client-1.18.1-20211210.034407-srg.jar%2353!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:86) ~[client-1.18.1-20211210.034407-srg.jar%2353!:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:668) ~[client-1.18.1-20211210.034407-srg.jar%2353!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[client-1.18.1-20211210.034407-srg.jar%2353!:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}

-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 2131876336 bytes (2033 MiB) / 4060086272 bytes (3872 MiB) up to 12884901888 bytes (12288 MiB)
	CPUs: 20
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i9-10900KF CPU @ 3.70GHz
	Identifier: Intel64 Family 6 Model 165 Stepping 5
	Microarchitecture: unknown
	Frequency (GHz): 3.70
	Number of physical packages: 1
	Number of physical CPUs: 10
	Number of logical CPUs: 20
	Graphics card #0 name: NVIDIA GeForce RTX 2080 Ti
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1e07
	Graphics card #0 versionInfo: DriverVersion=30.0.14.7196
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Memory slot #2 capacity (MB): 16384.00
	Memory slot #2 clockSpeed (GHz): 2.67
	Memory slot #2 type: DDR4
	Memory slot #3 capacity (MB): 16384.00
	Memory slot #3 clockSpeed (GHz): 2.67
	Memory slot #3 type: DDR4
	Virtual memory max (MB): 75063.97
	Virtual memory used (MB): 22913.21
	Swap memory total (MB): 9728.00
	Swap memory used (MB): 3.27
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx12288m -Xms256m
	Server Running: true
	Player Count: 1 / 8; [ServerPlayer['SirSpongington'/311, l='ServerLevel[New World]', x=62.65, y=71.00, z=-37.91, removed=KILLED]]
	Data Packs: vanilla, mod:forge, mod:schoolsofmagic
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'; Server brand changed to 'forge'
	ModLauncher: 9.0.7+91+master.8569cdf
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		javafml@null
	Mod List: 
		client-1.18.1-20211210.034407-srg.jar             |Minecraft                     |minecraft                     |1.18.1              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		forge-1.18.1-39.0.6-universal.jar                 |Forge                         |forge                         |39.0.6              |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		SchoolsOfMagic1.18.1-3.0.04.jar                   |Schools of Magic: Second Semes|schoolsofmagic                |3.0.02              |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: bf6543f7-9764-43ab-8fef-d9d34fc6a3fe
	FML: 39.0
	Forge: net.minecraftforge:39.0.6

Might be doing something wrong but I did try a few different versions of forge but same result

**Comment by Gaxon1** [comment]
Confirmed on Forge 39.0.5 as well
Everytime I click the respawn button the error and disconnect error occurs.

`[13:16:23] [Server thread/ERROR]: Exception caught during firing event: LazyOptional must not be empty!
        Index: 5
        Listeners:
                0: HIGH
                1: ASM: class dev.architectury.event.forge.EventHandlerImplCommon event(Lnet/minecraftforge/event/entity/player/PlayerEvent$Clone;)V
                2: NORMAL
                3: ASM: class com.cartoonishvillain.incapacitated.events.ForgeEvents playerCloneEvent(Lnet/minecraftforge/event/entity/player/PlayerEvent$Clone;)V
                4: ASM: com.github.alexthe666.citadel.server.CitadelEvents@591ca65 onPlayerClone(Lnet/minecraftforge/event/entity/player/PlayerEvent$Clone;)V
                5: ASM: class com.paleimitations.schoolsofmagic.common.data.capabilities.quest_data.QuestDataProvider$Events onClone(Lnet/minecraftforge/event/entity/player/PlayerEvent$Clone;)V
                6: ASM: class com.paleimitations.schoolsofmagic.common.data.capabilities.magic_data.MagicDataProvider$Events onClone(Lnet/minecraftforge/event/entity/player/PlayerEvent$Clone;)V
                7: net.minecraftforge.eventbus.EventBus$$Lambda$4138/0x0000000801683710@7944f957
                8: ASM: stepsword.mahoutsukai.handlers.ServerHandler@19a6e307 playerClone(Lnet/minecraftforge/event/entity/player/PlayerEvent$Clone;)V
                9: ASM: class com.verdantartifice.primalmagick.common.events.PlayerEvents playerCloneEvent(Lnet/minecraftforge/event/entity/player/PlayerEvent$Clone;)V
                10: ASM: top.theillusivec4.curios.common.event.CuriosEventHandler@4ccd3e99 playerClone(Lnet/minecraftforge/event/entity/player/PlayerEvent$Clone;)V
                11: LOWEST
                12: ASM: class ovh.corail.tombstone.event.EventHandler onClone(Lnet/minecraftforge/event/entity/player/PlayerEvent$Clone;)V
java.lang.IllegalArgumentException: LazyOptional must not be empty!
        at TRANSFORMER/schoolsofmagic@3.0.05/com.paleimitations.schoolsofmagic.common.data.capabilities.quest_data.QuestDataProvider$Events.lambda$onClone$0(QuestDataProvider.java:74)
        at TRANSFORMER/forge@39.0.5/net.minecraftforge.common.util.LazyOptional.orElseThrow(LazyOptional.java:295)
        at TRANSFORMER/schoolsofmagic@3.0.05/com.paleimitations.schoolsofmagic.common.data.capabilities.quest_data.QuestDataProvider$Events.onClone(QuestDataProvider.java:74)
        at net.minecraftforge.eventbus.ASMEventHandler_577_Events_onClone_Clone.invoke(.dynamic)
        at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
        at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
        at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
        at TRANSFORMER/forge@39.0.5/net.minecraftforge.event.ForgeEventFactory.onPlayerClone(ForgeEventFactory.java:483)
        at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.level.ServerPlayer.m_9015_(ServerPlayer.java:1147)
        at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.players.PlayerList.m_11236_(PlayerList.java:418)
        at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.network.ServerGamePacketListenerImpl.m_6272_(ServerGamePacketListenerImpl.java:1262)
        at TRANSFORMER/minecraft@1.18.1/net.minecraft.network.protocol.game.ServerboundClientCommandPacket.m_5797_(ServerboundClientCommandPacket.java:24)
        at TRANSFORMER/minecraft@1.18.1/net.minecraft.network.protocol.game.ServerboundClientCommandPacket.m_5797_(ServerboundClientCommandPacket.java:6)
        at TRANSFORMER/minecraft@1.18.1/net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:21)
        at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.TickTask.run(TickTask.java:18)
        at TRANSFORMER/minecraft@1.18.1/net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:151)
        at TRANSFORMER/minecraft@1.18.1/net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23)
        at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:765)
        at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:161)
        at TRANSFORMER/minecraft@1.18.1/net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:125)
        at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:748)
        at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:742)
        at TRANSFORMER/minecraft@1.18.1/net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:110)
        at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:727)
        at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:672)
        at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258)
        at java.base/java.lang.Thread.run(Thread.java:833)

[13:16:23] [Server thread/FATAL]: Error executing task on Server
java.lang.IllegalArgumentException: LazyOptional must not be empty!
        at com.paleimitations.schoolsofmagic.common.data.capabilities.quest_data.QuestDataProvider$Events.lambda$onClone$0(QuestDataProvider.java:74) ~[SchoolsOfMagic1.18.1-3.0.05.jar%23208!:3.0.05]
        at net.minecraftforge.common.util.LazyOptional.orElseThrow(LazyOptional.java:295) ~[forge-1.18.1-39.0.5-universal.jar%23266!:?]
        at com.paleimitations.schoolsofmagic.common.data.capabilities.quest_data.QuestDataProvider$Events.onClone(QuestDataProvider.java:74) ~[SchoolsOfMagic1.18.1-3.0.05.jar%23208!:3.0.05]
        at net.minecraftforge.eventbus.ASMEventHandler_577_Events_onClone_Clone.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!:?]
        at net.minecraftforge.event.ForgeEventFactory.onPlayerClone(ForgeEventFactory.java:483) ~[forge-1.18.1-39.0.5-universal.jar%23266!:?]
        at net.minecraft.server.level.ServerPlayer.m_9015_(ServerPlayer.java:1147) ~[server-1.18.1-20211210.034407-srg.jar%23262!:?]
        at net.minecraft.server.players.PlayerList.m_11236_(PlayerList.java:418) ~[server-1.18.1-20211210.034407-srg.jar%23262!:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.m_6272_(ServerGamePacketListenerImpl.java:1262) ~[server-1.18.1-20211210.034407-srg.jar%23262!:?]
        at net.minecraft.network.protocol.game.ServerboundClientCommandPacket.m_5797_(ServerboundClientCommandPacket.java:24) ~[server-1.18.1-20211210.034407-srg.jar%23262!:?]
        at net.minecraft.network.protocol.game.ServerboundClientCommandPacket.m_5797_(ServerboundClientCommandPacket.java:6) ~[server-1.18.1-20211210.034407-srg.jar%23262!:?]
        at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:21) ~[server-1.18.1-20211210.034407-srg.jar%23262!:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.18.1-20211210.034407-srg.jar%23262!:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:151) ~[server-1.18.1-20211210.034407-srg.jar%23262!:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.18.1-20211210.034407-srg.jar%23262!:?]
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:765) ~[server-1.18.1-20211210.034407-srg.jar%23262!:?]
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:161) ~[server-1.18.1-20211210.034407-srg.jar%23262!:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:125) ~[server-1.18.1-20211210.034407-srg.jar%23262!:?]
        at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:748) ~[server-1.18.1-20211210.034407-srg.jar%23262!:?]
        at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:742) ~[server-1.18.1-20211210.034407-srg.jar%23262!:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:110) ~[server-1.18.1-20211210.034407-srg.jar%23262!:?]
        at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:727) ~[server-1.18.1-20211210.034407-srg.jar%23262!:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:672) ~[server-1.18.1-20211210.034407-srg.jar%23262!:?]
        at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[server-1.18.1-20211210.034407-srg.jar%23262!:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
[13:16:23] [Server thread/ERROR]: Exception caught during firing event: null
        Index: 11
        Listeners:
                0: HIGHEST
                1: ASM: class binary404.mystictools.common.effect.EffectFreeze onLivingTick(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
                2: NORMAL
                3: ASM: class com.cartoonishvillain.vdm.events.ForgeEvents activateWrong(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
                4: ASM: class com.cartoonishvillain.vdm.events.ForgeEvents Flammable(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
                5: ASM: com.lothrazar.mountedpearl.ModMountedPearl@4077d82d onEntityUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
                6: ASM: atomicstryker.infernalmobs.common.EntityEventHandler@195a1f17 onEntityLivingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
                7: ASM: com.lothrazar.horsestandstill.EventHorseStandStill@476f284b onHit(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
                8: ASM: com.github.alexthe666.citadel.server.CitadelEvents@591ca65 onEntityUpdateDebug(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
                9: ASM: com.github.alexthe666.alexsmobs.event.ServerEvents@1f2b9ffc onLivingUpdateEvent(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
                10: ASM: class com.paleimitations.schoolsofmagic.common.data.capabilities.quest_data.QuestDataProvider$Events onUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
                11: ASM: class com.paleimitations.schoolsofmagic.common.data.capabilities.magic_data.MagicDataProvider$Events onUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
                12: ASM: class com.paleimitations.schoolsofmagic.common.data.capabilities.conjured_data.ConjuredDataProvider$Events onUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
                13: ASM: elucent.rootsclassic.event.ComponentSpellsEvent@55b86b0f onLivingTick(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
                14: net.minecraftforge.eventbus.EventBus$$Lambda$4138/0x0000000801683710@2140a403
                15: ASM: stepsword.mahoutsukai.handlers.ServerHandler@19a6e307 livingEvent(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
                16: ASM: class com.verdantartifice.primalmagick.common.events.PlayerEvents livingTick(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
                17: ASM: com.mactso.regrowth.events.MoveEntityEvent@7bdd07de handleEntityMoveEvents(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
                18: ASM: top.theillusivec4.curios.common.event.CuriosEventHandler@4ccd3e99 tick(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
                19: ASM: com.lothrazar.villagertools.ItemEvents@4c292064 onLivingUpdateEvent(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
                20: ASM: squeek.appleskin.network.SyncHandler@314e055 onLivingUpdateEvent(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
                21: net.minecraftforge.eventbus.EventBus$$Lambda$4138/0x0000000801683710@6472105
                22: net.minecraftforge.eventbus.EventBus$$Lambda$4138/0x0000000801683710@2189c317
                23: ASM: class thut.core.common.world.mobs.data.SyncHandler EntityUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
                24: LOWEST
                25: ASM: class ovh.corail.tombstone.event.EventHandler onLivingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
java.lang.IllegalStateException
        at TRANSFORMER/forge@39.0.5/net.minecraftforge.common.util.LazyOptional.orElseThrow(LazyOptional.java:295)
        at TRANSFORMER/schoolsofmagic@3.0.05/com.paleimitations.schoolsofmagic.common.data.capabilities.magic_data.MagicDataProvider$Events.onUpdate(MagicDataProvider.java:120)
        at net.minecraftforge.eventbus.ASMEventHandler_599_Events_onUpdate_LivingUpdateEvent.invoke(.dynamic)
        at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
        at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
        at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
        at TRANSFORMER/forge@39.0.5/net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:283)
        at TRANSFORMER/minecraft@1.18.1/net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2204)
        at TRANSFORMER/minecraft@1.18.1/net.minecraft.world.entity.player.Player.m_8119_(Player.java:234)
        at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:439)
        at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.network.ServerGamePacketListenerImpl.m_9933_(ServerGamePacketListenerImpl.java:206)
        at TRANSFORMER/minecraft@1.18.1/net.minecraft.network.Connection.m_129483_(Connection.java:233)
        at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:142)
        at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:882)
        at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:328)
        at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:808)
        at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:668)
        at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258)
        at java.base/java.lang.Thread.run(Thread.java:833)

[13:16:24] [Server thread/WARN]: Failed to handle packet for /***.***.**.***:54567
net.minecraft.ReportedException: Ticking player
        at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:502) ~[server-1.18.1-20211210.034407-srg.jar%23262!:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.m_9933_(ServerGamePacketListenerImpl.java:206) ~[server-1.18.1-20211210.034407-srg.jar%23262!:?]
        at net.minecraft.network.Connection.m_129483_(Connection.java:233) ~[server-1.18.1-20211210.034407-srg.jar%23262!:?]
        at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:142) ~[server-1.18.1-20211210.034407-srg.jar%23262!:?]
        at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:882) ~[server-1.18.1-20211210.034407-srg.jar%23262!:?]
        at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:328) ~[server-1.18.1-20211210.034407-srg.jar%23262!:?]
        at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:808) ~[server-1.18.1-20211210.034407-srg.jar%23262!:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:668) ~[server-1.18.1-20211210.034407-srg.jar%23262!:?]
        at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[server-1.18.1-20211210.034407-srg.jar%23262!:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.IllegalStateException
        at net.minecraftforge.common.util.LazyOptional.orElseThrow(LazyOptional.java:295) ~[forge-1.18.1-39.0.5-universal.jar%23266!:?]
        at com.paleimitations.schoolsofmagic.common.data.capabilities.magic_data.MagicDataProvider$Events.onUpdate(MagicDataProvider.java:120) ~[SchoolsOfMagic1.18.1-3.0.05.jar%23208!:3.0.05]
        at net.minecraftforge.eventbus.ASMEventHandler_599_Events_onUpdate_LivingUpdateEvent.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!:?]
        at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:283) ~[forge-1.18.1-39.0.5-universal.jar%23266!:?]
        at net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2204) ~[server-1.18.1-20211210.034407-srg.jar%23262!:?]
        at net.minecraft.world.entity.player.Player.m_8119_(Player.java:234) ~[server-1.18.1-20211210.034407-srg.jar%23262!:?]
        at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:439) ~[server-1.18.1-20211210.034407-srg.jar%23262!:?]
        ... 9 more
[13:16:24] [Server thread/INFO]: Gaxan lost connection: Internal server error
[13:16:24] [Server thread/INFO]: Gaxan left the game`

**Comment by jambox5** [comment]
came to post same issue, still a problem with SchoolsOfMagic1.18 3.0.05, Forge version makes no diff

**Comment by UdoMorgenstern** [comment]
SchoolsOfMagic1.18.1-3.0.06 - no crash anymore, but all spells are removed from wand, and players are back to level 1
https://github.com/pale-imitations/schools_of_magic/issues/8
